### PR TITLE
AV-101381 Removed ovftool bundle for vmware security compliance

### PR DESCRIPTION
**Pull request by yograjshisode**

### CODE REVIEW

**Review by manojkumarjain — APPROVED** [review]

**Comment by sabandi** [comment]
Are the customer expected bring their own ovftool ?

**Comment by yograjshisode** [comment]
@sabandi Removing current VMware-ovftool-4.4.0-15722219-lin.x86_64.bundle for AV-101381 temporary. Will bundle the correct version of ovftool which is compatible with controller and VMware security compliance. Created ticket AV-102264 to track it.

**Comment by sabandi** [comment]
@yograjshisode removing it without an alternative will render this role broken. I think we should add the alternative in this PR only. @chaitanyaavi @manojkumarjain thoughts?

**Comment by chaitanyaavi** [comment]
@sabandi +1

**Review by manojkumarjain — APPROVED** [review]

**Pull request merged**
